# Generated by Django 5.1.5 on 2025-01-29 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100, unique=True)),
                ('review_title', models.CharField(max_length=200, unique=True)),
                ('platform_reviewed_on', models.IntegerField(choices=[(1, 'Xbox'), (2, 'PlayStation'), (3, 'Nintendo'), (4, 'PC')], default=None)),
                ('index_excerpt', models.TextField()),
                ('full_review', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('star_rating', models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], default=None)),
                ('co_op_mode_couch', models.BooleanField(default=False)),
                ('co_op_mode_online', models.BooleanField(default=False)),
                ('pegi_rating', models.IntegerField(choices=[(1, '3'), (2, '7'), (3, '12'), (4, '16'), (5, '18')], default=None)),
                ('platform_availability_xbox', models.BooleanField(default=False)),
                ('platform_availability_playstation', models.BooleanField(default=False)),
                ('platform_availability_nintendo', models.BooleanField(default=False)),
                ('platform_availability_pc', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-game_title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.review')),
            ],
            options={
                'ordering': ['-review'],
            },
        ),
    ]
