# Generated by Django 5.1.5 on 2025-01-30 14:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='missingboxart', max_length=255, verbose_name='image'),
        ),
    ]
