# Generated by Django 5.1.5 on 2025-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pegi_rating',
            field=models.IntegerField(blank=True, choices=[(1, '3'), (2, '7'), (3, '12'), (4, '16'), (5, '18')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='platform_reviewed_on',
            field=models.IntegerField(blank=True, choices=[(1, 'Xbox'), (2, 'PlayStation'), (3, 'Nintendo'), (4, 'PC')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], null=True),
        ),
    ]
