# Generated by Django 5.1.5 on 2025-02-06 09:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_pegi_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='missingboxart', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pegi_rating',
            field=models.IntegerField(blank=True, choices=[(1, '3'), (2, '7'), (3, '12'), (4, '16'), (5, '18')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='platform_reviewed_on',
            field=models.IntegerField(choices=[(1, 'Xbox'), (2, 'PlayStation'), (3, 'Nintendo'), (4, 'PC')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], default=None),
        ),
    ]
